### ISSUE TITLE
Nicer destroying possible?

### ISSUE THREAD

**Issue by ctaepper** [ngneat/bind-query-params#12]
Is there maybe a smart way to destroy the param manager using your UntilDestroyed lib? So I would not have to have an ngOnDestroy function in each component where I use this lib.

**Comment by NetanelBasal** [comment]
The `connect` should return the instance because it exposes additional methods. I'll think about it.

**Comment by NetanelBasal** [comment]
I don't think doing something like this is better:

```ts
class Comp {
  private manager = this.factory
    .create<Params>([...])

  constructor(private factory: BindQueryParamsFactory) {}

  ngOnInit() {
    this.manager.connect().pipe(untilDestroyed(this)).subscribe();
  }
}
```
