### ISSUE TITLE
FormControl with object type issue

### ISSUE THREAD

**Issue by weilinzung** [ngneat/bind-query-params#15]
FormGroup has one of control with Object
```
   this.form = this.formBuilder.group({
      search: [null],
      users: [
        { selectAll: false, selected: [12,23] }
      ]
    });
```

bindQueryParams
```
   { queryKey: 'users', type: 'object' }
```

URL becomes: 
```
http://localhost:4200/page?search=string&users=%5Bobject%20Object%5D
```

Can I verify if anything wrong with the object type? or does it supoort? Thanks.

**Comment by NetanelBasal** [comment]
You need to use parser and serializer

**Comment by weilinzung** [comment]
@NetanelBasal thanks for the quick reply.

I tried using a serializer. but that would update the form value into a string, rather than as an object.

I am new to this lib, could you provide a better example of how to deal with my case? Much thanks!

**Comment by NetanelBasal** [comment]
Try the latest release. Note that you should also use the parser option:

```ts
parser: JSON.parse
```
