### ISSUE TITLE
Deleting a form control value does not remove the query param key 

### ISSUE THREAD

**Issue by DominicSachs** [ngneat/bind-query-params#16]
I updated your stackblitz to the latest versions. Now deleting a form control value does not remove the query param key anymore.

If you remove the search text, the url looks like: https://bind-query-params-qehljm.stackblitz.io/products?searchTerm=

Original: https://stackblitz.com/edit/bind-query-params
Latest Versions:  https://stackblitz.com/edit/bind-query-params-qehljm

**Comment by NetanelBasal** [comment]
Thanks for the report.
