### ISSUE TITLE
How to parse value before send to URL?

### ISSUE THREAD

**Issue by dev054** [ngneat/bind-query-params#3]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a `<input matDatepicker>` and when I change the date it sends the `Date` to the url.

## Expected behavior
I'd like to know if there's an option to _parse_ it (in this case to `string`) before send it to the url. I've already tried to use https://github.com/ngneat/bind-query-params#parser, however it seems that `parser` is only called on initialization.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ewwssg

## What is the motivation / use case for changing the behavior?
I'd like to have an ISO string in URL, but keeping Date in my `FormControl`.

## Environment

<pre><code>
Angular version: 11x
</pre></code>

Others:
Thanks for this awesome lib :pray:.

**Comment by NetanelBasal** [comment]
You mean serializer. You can create a PR that adds a `serializer` option.

**Comment by NetanelBasal** [comment]
If you want to fix your example you can just do `parser: value => new Date(value)`

**Comment by dev054** [comment]
> If you want to fix your example you can just do `parser: value => new Date(value)`

Aha, yes. I just noticed that the `matDatepicker` waits for a `Date`.

> You mean serializer. You can create a PR that adds a `serializer` option.
I’m afraid I don’t have the knowledge and time to implement this, so I'll leave it to someone more experienced.

Btw, just to confirm... with the `serialized` option, using the example above, we would do something like this:

```
readonly bindQueryParamsManager = this.bindQueryParamsFactory
  .create<Filters>([
    { queryKey: 'test', parser: value => new Date(value), serializer: value => value.toISOString() },
  ])
  .connect(this.formGroup);
```

... and then the result in `test` (`FormControl`) would be a `Date` while a `String date`(`yyyy-mm-dd`) in query params?

**Comment by NetanelBasal** [comment]
Correct
